const { readdirSync, writeFileSync, lstatSync, readFileSync } = require("fs");
const { join } = require("path");

// Plugins directory for TS/service files
const pluginsDir = "./src/app/plugins";
// Where the JSON configs are stored
const assetsDir = "./src/assets/plugins"; // <-- point to assets

const generatedFile = "./src/app/generated/plugins.gen.ts";

// Read all folders in pluginsDir
const folders = readdirSync(pluginsDir).filter(f => {
  return lstatSync(join(pluginsDir, f)).isDirectory();
});

let imports = [];
let registryEntries = [];

console.log("[INFO] Watching plugins")

folders.forEach(folder => {
  try {
    console.log(`[INFO] registering ${folder}`)
    // Adjusted JSON path to assets
    const pluginJsonPath = join(assetsDir, folder, "plugin.json");
    const config = JSON.parse(readFileSync(pluginJsonPath, "utf-8"));

    const { name, serviceFile, serviceClass } = config;
    const servicePath = `../plugins/${folder}/${serviceFile.replace(/\.ts$/, "")}`;

    imports.push(`import { ${serviceClass} } from '${servicePath}';`);
    registryEntries.push(`{ name: '${name}', service: ${serviceClass} }`);
  } catch (err) {
    console.warn(`Skipping plugin "${folder}" due to error reading plugin.json:`, err.message);
  }
});

const output = `// Auto-generated by load-plugins.js
import { Injectable } from '@angular/core';
${imports.join("\n")}

// Registry of all plugins with their names and service classes
export const PLUGIN_REGISTRY = [
  ${registryEntries.join(",\n  ")}
];

// Optional: re-export all plugin services
export {
  ${registryEntries.map(e => e.match(/service: (\w+)/)[1]).join(",\n  ")}
};
`;

writeFileSync(generatedFile, output, { encoding: "utf-8" });
console.log("Generated plugin registry:");
console.log(registryEntries);
